Update appversion, add selector
GoogleCloudPlatform/github-actions pull request #194
Opened 2020-10-10 11:58 UTC by explooosion

Update `appVersion` from `apps/v1beta` to `apps/v1`, add `selector.matchLabels.app`.

![image](https://user-images.githubusercontent.com/13682994/95654432-8b673800-0b32-11eb-9ab3-db780c19263d.png)

![image](https://user-images.githubusercontent.com/13682994/95654433-8e622880-0b32-11eb-8ba3-3500beb9ce2a.png)

2020-10-12 20:32 UTC, bb-glitch approved these changes

2020-10-12 20:32 UTC, bb-glitch requested changes
explooosion:fix/gke-deployment-appversion

2020-10-14 03:32 UTC, explooosion commented
> explooosion:fix/gke-deployment-appversion

Hi @bb-glitch , 
Sorry, I didn’t understand you. Should I change anything ? thank you for your reply.

2020-10-23 23:09 UTC, averikitsch approved these changes

2020-10-23 23:09 UTC, averikitsch commented
Thanks!

2020-10-23 23:09 UTC, merged